ndb chef fixes

diff --git a/scripts/chef-repo/cookbooks/ndb/templates/default/mgm-server-start.sh.erb b/scripts/chef-repo/cookbooks/ndb/templates/default/mgm-server-start.sh.erb
--- a/scripts/chef-repo/cookbooks/ndb/templates/default/mgm-server-start.sh.erb
+++ b/scripts/chef-repo/cookbooks/ndb/templates/default/mgm-server-start.sh.erb
@@ -1,76 +1,38 @@
 #!/bin/sh 
 
-
 USERID=`id | sed -e 's/).*//; s/^.*(//;'`
-if [ "X$USERID" != "Xroot" ]; then
- if [ "X$USERID" = "Xroot" ]; then
-   echo ""
-   echo "You started cluster as user: 'root'."
-   echo "You should start cluster as user: 'root'."
+if [ "X$USERID" != "X<%= node[:ndb][:user] %>" ]; then
+   echo "You should have started the cluster as user: '<%= node[:ndb][:user] %>'."
    echo "If you continue, you will change ownership of database files"
-   echo "from 'root' to 'root'."
-# TODO: return -2
- else
-   echo ""
-   echo "You started the cluster as user: '$USERID'."
-   echo "You should start the cluster as user: 'root'."
-   echo "If you continue, you will change ownership of database files"
-   echo "from 'root' to '$USERID'."
-# TODO: return -2
- fi
- 
- echo ""
-start_as_wrong_user() 
-{
-  echo -n "Do you really want to start the cluster as user 'root'? y/n/h(help) "
-  read ACCEPT
-  case $ACCEPT in
-   y | Y)
-      ;;
-   n | N)
-      echo ""
-      echo "Bye.."
-      echo ""
-      exit 1
-      ;;
-    *)
-      echo ""
-      echo -n "Please enter 'y' or 'n'." 
-      start_as_wrong_user
-      ;;
-   esac
-}
-start_as_wrong_user
+   echo "from '<%= node[:ndb][:user] %>' to '$USERID'."
+   exit -3
+fi  
 
+echo "" 
+echo "Testing to see if a cluster is already running on <%= @connect_string %> ..." 
+echo "" 
+<%= @mysql_dir %>/bin/ndb_mgm -c <%= @connect_string %> -e \"show\"> /dev/null
 
+if [ $? -eq 0 ] ; then
+    echo ""      
+    echo "A management server is already running on <%= @connect_string %>" 
+    echo "" 	
+    exit 2
 fi
-
-
-  echo "" 
-  echo "Testing to see if a cluster is already running on host 'cloud11:1186' ..." 
-  echo "" 
-  <%= @mysql_dir %>/bin/ndb_mgm -c cloud11:1186 -t 2 -e show 1> /dev/null
-
-  if [ $? -eq 0 ] ; then
-      echo ""      
-      echo "A management server is already running on cloud11:1186" 
-      echo "" 	
-      exit 2
-  fi
 
 
 if [ ! -e <%= @mysql_dir %>/bin/ndb_mgmd ] ; then
-  echo "Error: could not find file: <%= @mysql_dir %>/bin/ndb_mgmd"
-  exit 3
+    echo "Error: could not find file: <%= @mysql_dir %>/bin/ndb_mgmd"
+    exit 3
 fi
 
-<%= @mysql_dir %>/bin/ndb_mgmd -f  <%= @ndb_dir %>/config.ini  --configdir=<%= @ndb_dir %>/mgmd4 --reload  
+<%= @mysql_dir %>/bin/ndb_mgmd -f  <%= @ndb_dir %>/config.ini  --configdir=<%= @ndb_dir %>/mgmd --reload  
 RES=`echo $?`
 if [ $RES -ne 0 ] ; then
     echo ""
     echo "Error when starting the management server: $?."
     echo ""
-    exit 2
+    exit 1
 fi
 exit $RES
 
